script/seed.js, server/api/ships.js, server/db/models/index.js, server/db/models/ship.js
=> routes ships users

package.json, script/seed.js
=> testing build for travis

client/components/Pages/CartPage.js, client/components/Pages/ShipList.js, client/components/Pages/SingleShipPage.js, client/components/cards/CheckoutSummaryCard.js, client/components/cards/Shipcard.js, client/store/cart.js, client/store/ship.js
=> made a lot of components

client/routes.js, package-lock.json
=> wrong commit

client/components/Pages/SingleShipPage.js
=> Single Ship Page

client/components/Pages/SingleShipPage.js, client/routes.js
=> fixed routes so we can run the build

client/app.js, client/components/cards/Shipcard.js, client/components/cards/style/shipCard.css, package-lock.json, package.json, webpack.config.js
=> added ship card

client/app.js, client/components/navbar.js, client/components/style/navbar.css
=> finished navbar

client/components/Pages/ShipList.js, client/components/navbar.js, client/index.js, client/routes.js
=> Fixing routes

client/components/Pages/CartPage.js, client/routes.js, client/store/cart.js, server/db/models/cart.js, server/db/models/index.js
=> some small changes

client/app.js, client/components/Pages/ReviewList.js, client/routes.js, client/store/review.js, server/api/index.js, server/api/reviews.js, server/db/models/index.js, server/db/models/review.js
=> Working review

client/routes.js
=> fixed the routes again and commented out review routes

client/components/Pages/SingleShipPage.js, client/components/cards/Shipcard.js
=> got single ship page fixed up

client/components/Pages/SingleShipPage.js, client/components/cards/Shipcard.js, client/components/forms/CheckoutForm.js, client/components/user-home.js, client/routes.js, server/api/users.js, server/db/models/user.js
=> Login page

client/store/cart.js, server/api/users.js
=> added routes for cart

client/components/forms/CheckoutForm.js, client/components/forms/signUp.js, server/api/ships.spec.js, server/db/models/index.js, server/db/models/payment.js, server/db/models/ship.spec.js
=> added checkout form and some tests for the server side

client/components/Pages/SingleShipPage.js, client/components/forms/AddReview.js, client/components/forms/EditReview.js, client/components/forms/ReviewForm.js, client/store/review.js, server/api/reviews.js
=> pause add review

server/api/cart.js, server/api/index.js, server/api/reviews.js, server/db/models/cart.js, server/db/models/index.js, server/db/models/user.js
=> Checkout pages

client/routes.js
=> fixed logged in and logged out routes (small fix)

client/components/Pages/ShipList.js, client/components/cards/Shipcard.js, client/components/cards/style/shipCard.css, client/store/cart.js, package-lock.json, package.json, server/db/models/cart.js, server/db/models/index.js
=> Adding items

server/db/models/index.js, server/db/models/user.js
=> fixed some bugs

client/components/cards/Shipcard.js
=> fixed shipCard name

client/components/Pages/CartPage.js, client/components/cards/CartItems.js, client/store/cart/reducer.js, client/store/cart/thunk.js, server/api/cart.js
=> users can now remove from cart

client/components/Pages/SingleUserPage.js, client/components/cards/CartItems.js, client/components/cards/style/CartItems.css, client/components/navbar.js, client/components/style/singleUser.css, client/index.js, client/routes.js, client/store/cart/reducer.js, client/store/cart/thunk.js, client/store/user.js, script/seed.js, server/api/cart.js, server/api/users.js
=> Users can now change quantity and see subtotal change

client/components/Pages/SingleShipPage.js, client/store/cart/thunk.js, server/api/cart.js
=> users can add quantity from single page

client/components/forms/AddReview.js, client/components/forms/ReviewForm.js, package-lock.json
=> finished addReview

client/app.js, client/components/Pages/ShipList.js, client/components/cards/CartItems.js, client/components/cards/Shipcard.js, client/components/cards/style/CartItems.css, client/components/cards/style/shipCard.css, script/seed.js
=> fixed main page

package-lock.json
=> package json had missing brackets, fixed

client/app.js, client/components/Pages/Checkout.js, client/components/Pages/CheckoutForm.js, client/components/cards/style/CartItems.css, client/components/cards/style/shipCard.css, client/routes.js, package-lock.json, package.json, script/seed.js, server/db/models/ship.js, server/index.js, server/server.js
=> added ships information

client/components/Pages/ShipList.js, client/components/Pages/SingleShipPage.js, client/components/cards/Shipcard.js, client/store/review.js
=> set session

client/components/Pages/ShipList.js, client/components/cards/Shipcard.js, client/store/index.js, package.json
=> Working on session

client/components/Pages/CartPage.js, client/components/cards/CartItemForGuest.js, client/components/cards/Shipcard.js, client/components/cards/style/CartItems.css
=> separated guestcart from usercart

client/components/cards/style/CartItems.css, client/components/cards/style/shipCard.css, client/components/style/singleShip.css, public/style.css, script/seed.js, server/api/wishlist.js
=> finished backend for wishlist

client/routes.js
=> fixing ShipCard.js name from Shipcard.js

client/components/Pages/WishListPage.js
=> Fixing WishList names for Heroku

client/components/Pages/CheckoutForm.js, client/components/Pages/HomePage.js, client/components/Pages/SingleShipPage.js, client/components/cards/CheckoutSummaryCard.js, client/components/cards/ShipCard.js, client/components/navbar.js, client/components/style/checkout.css, client/components/style/homePage.css, client/components/style/singleShip.css, script/seed.js
=> Styling fix ups

client/components/Pages/CartPage.js, client/components/navbar.js, client/store/cart/thunk.js, client/store/index.js, server/api/cart.js
=> CartPageRefresh

client/components/navbar.js
=> fixed error

client/components/Pages/CartPage.js, client/components/Pages/CheckoutForm.js, client/components/Pages/HomePage.js, client/components/style/homePage.css
=> Minor fixes

client/components/Pages/CartPage.js, client/components/Pages/SingleShipPage.js, client/components/cards/CartItems.js, client/components/cards/ShipCard.js, client/store/cart/thunk.js, server/api/cart.js
=> Refreshing cart

client/components/Pages/CartPage.js, client/components/Pages/SingleShipPage.js, client/components/cards/ShipCard.js
=> fixed get price from local storage error
